apiVersion: v1
kind: Service
metadata:
  name: leaderboard
  labels:
    app: leaderboard
spec:
  type: ClusterIP
  selector:
    app: leaderboard
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
