apiVersion: v1
kind: Service
metadata:
  name: routes
  namespace: final-project
  labels:
    app: routes
spec:
  type: ClusterIP
  selector:
    app: routes
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
