apiVersion: apps/v1
kind: Deployment
metadata:
  name: maps
  namespace: final-project
  labels:
    app: maps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maps
  template:
    metadata:
      labels:
        app: maps
    spec:
      containers:
        - name: maps
          image: trailbox-maps:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
            - containerPort: 8081
          env:
            - name: PORT
              value: "50051"
            - name: SERVICE_NAME
              value: map
            - name: SERVICE_ADDRESS
              value: map-service.final-project.svc.cluster.local
            - name: SERVICE_HEALTH_PATH
              value: /health
            - name: CONSUL_HTTP_ADDR
              value: http://consul.final-project.svc.cluster.local:8500
            - name: DB_HOST
              value: postgres.final-project.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: trailbox-db-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: trailbox-db-secret
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: trailbox-db-secret
                  key: DB_NAME
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: map-service
  namespace: final-project
spec:
  selector:
    app: maps
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
