apiVersion: v1
kind: Service
metadata:
  name: workouts
  labels:
    app: workouts
spec:
  type: ClusterIP
  selector:
    app: workouts
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
