apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  namespace: final-project
  labels:
    app: reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - name: reviews
          image: trailbox/reviews:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              name: grpc
            - containerPort: 8081
              name: health
          env:
            - name: PORT
              value: "50051"
            - name: DB_HOST
              value: postgres.final-project.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: trailbox-db-secret
                  key: REVIEWS_DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: trailbox-db-secret
                  key: REVIEWS_DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: trailbox-db-secret
                  key: REVIEWS_DB_NAME
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 150m
              memory: 192Mi
            limits:
              cpu: 300m
              memory: 384Mi
