apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: final-project
  labels:
    app: reviews
spec:
  type: ClusterIP
  selector:
    app: reviews
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
