apiVersion: v1
kind: Secret
metadata:
  name: trailbox-db-secret
type: Opaque
stringData:
  DB_USER: trailbox
  DB_PASS: trailbox
  DB_NAME: trailbox
  USERS_DB_USER: users_app
  USERS_DB_PASS: users_pass
  USERS_DB_NAME: users_db
  ROUTES_DB_USER: routes_app
  ROUTES_DB_PASS: routes_pass
  ROUTES_DB_NAME: routes_db
  WORKOUTS_DB_USER: workouts_app
  WORKOUTS_DB_PASS: workouts_pass
  WORKOUTS_DB_NAME: workouts_db
  REVIEWS_DB_USER: reviews_app
  REVIEWS_DB_PASS: reviews_pass
  REVIEWS_DB_NAME: reviews_db
  LEADERBOARD_DB_USER: leaderboard_app
  LEADERBOARD_DB_PASS: leaderboard_pass
  LEADERBOARD_DB_NAME: leaderboard_db
  NOTIFICATIONS_DB_USER: notifications_app
  NOTIFICATIONS_DB_PASS: notifications_pass
  NOTIFICATIONS_DB_NAME: notifications_db
  MAPS_DB_USER: maps_app
  MAPS_DB_PASS: maps_pass
  MAPS_DB_NAME: maps_db
